---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Должен отображаться выбранный язык
  - При смене языка должна меняться валюта
  - При смене языка должен меняться язык описания в карточке товара
  - В карточке товара должна быть возможность просмотра дополнительных изображений в увеличенном размере
  - Должна быть кнопка возврата в каталог из карточки товара
  - При выборе категории должна быть возможность снова показать все товары
  - Должно быть какое-то подтверждение того, что товар добавлен в корзину
  - Должен быть личный кабинет пользователя
